# NUMPY BASICS

In [1]:
import numpy as np

In [2]:
#create a list
lst=[1,2,3,4,5]

In [3]:
print(lst)

[1, 2, 3, 4, 5]


In [4]:
#change list into array
arr=np.array(lst)

In [5]:
type(arr)

numpy.ndarray

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
#1-dim array
np.shape(arr)

(5,)

In [8]:
#create a list of 3
lst1=[1,2,3,4,5]
lst2=[9,8,5,6,7]
lst3=[3,5,7,4,2]

In [9]:
arr1=np.array([lst1,lst2,lst3,])

In [10]:
#2-dim array
arr1

array([[1, 2, 3, 4, 5],
       [9, 8, 5, 6, 7],
       [3, 5, 7, 4, 2]])

In [11]:
arr1.shape


(3, 5)

In [12]:
#Reshaping should be same value(i.e 15)
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 9],
       [8, 5, 6],
       [7, 3, 5],
       [7, 4, 2]])

In [13]:
arr1.reshape(15,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [9],
       [8],
       [5],
       [6],
       [7],
       [3],
       [5],
       [7],
       [4],
       [2]])

In [14]:
arr1.reshape(1,15)

array([[1, 2, 3, 4, 5, 9, 8, 5, 6, 7, 3, 5, 7, 4, 2]])

# Indexing of array

In [15]:
#1-dim indexing
arr_1=np.array([1,2,3,4,5,6,7,8])

In [16]:
arr_1[6]

7

In [17]:
arr_1[2:7]

array([3, 4, 5, 6, 7])

In [18]:
#2-dim indexing
#1strow=0,2ndrow=1,3rdrow=2;
#1stcol=0,2ndcol=1,3rdcol=2
arr1

array([[1, 2, 3, 4, 5],
       [9, 8, 5, 6, 7],
       [3, 5, 7, 4, 2]])

In [19]:
arr1[1:3,2:4]

array([[5, 6],
       [7, 4]])

In [20]:
arr1[0:,0:2]

array([[1, 2],
       [9, 8],
       [3, 5]])

In [31]:
arr=np.arange(1,10)

In [32]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr[4:]=200

In [34]:
arr

array([  1,   2,   3,   4, 200, 200, 200, 200, 200])

In [35]:
#reference cell 
arr_ref=arr

In [36]:
arr_ref[4:]=500

In [37]:
arr_ref

array([  1,   2,   3,   4, 500, 500, 500, 500, 500])

In [38]:
arr

array([  1,   2,   3,   4, 500, 500, 500, 500, 500])

In [39]:
#copy()
arr_ref2=arr.copy()

In [40]:
arr_ref2[4:]=1000

In [41]:
arr_ref2

array([   1,    2,    3,    4, 1000, 1000, 1000, 1000, 1000])

In [42]:
#no change in the base location
arr

array([  1,   2,   3,   4, 500, 500, 500, 500, 500])

In [67]:
#random distribution-uniform dist values
np.random.rand(4,3)

array([[0.90689512, 0.83099384, 0.85420406],
       [0.13833341, 0.24973341, 0.99043664],
       [0.44512314, 0.40930336, 0.59085385],
       [0.11932137, 0.47924938, 0.66656243]])

In [64]:
#standard normal dist values
np.random.randn(5,3)

array([[ 0.57865166, -0.53843369,  0.56115726],
       [ 0.69786442,  0.17784236,  1.27423833],
       [ 0.35606445,  1.04726178, -0.26808822],
       [ 0.62101957, -0.31127684,  1.87720173],
       [-0.88688586,  0.06325844, -0.66559111]])

In [68]:
np.random.randint(1,989,10)

array([667, 820, 851, 138, 566, 627, 902, 538, 256, 947])

In [70]:
np.random.randint(1,989,10).reshape(5,2)

array([[700, 963],
       [ 53, 662],
       [406,  66],
       [946, 515],
       [694, 247]])

In [78]:
np.random.random_sample((4,3))

array([[0.91212434, 0.13727976, 0.95587822],
       [0.9928996 , 0.96372644, 0.38207448],
       [0.5758122 , 0.76719115, 0.62099141],
       [0.81489149, 0.82109733, 0.6109126 ]])

In [61]:
np.linspace(1,15,num=50)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [55]:
a=arr_ref*arr_ref2

In [56]:
a


array([     1,      4,      9,     16, 500000, 500000, 500000, 500000,
       500000])

In [58]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [59]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])